name: Format & Lint
on:
  push:
  pull_request:

jobs:
  format-lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Format
        run: make fmt
      - name: Lint
        run: make lint